### ISSUE TITLE
wave packet control for heater

### ISSUE THREAD

**Issue by im-pro-at** [trueserve/reflowOvenController#2]
First of all nice work cleaning up the code from 0XPIT ;-)

Here the part i did not understand:
```
// --ZX ISR--------------------------------------------------------------------
// per ZX, process one channel per interrupt only
// NB: use native port IO instead of digitalWrite for better performance
// true: using digitalWrite again for better compatibility
void zeroCrossingIsr(void)
{
  static uint8_t ch = 0;

  // reset phase control timer
  phaseCounter = 0;
  TCNT1 = 0;
  
  zeroCrossTicks++;

  // calculate wave packet parameters
  Channels[ch].state += Channels[ch].target;
  if (Channels[ch].state >= 100) {
    Channels[ch].state -= 100;
    Channels[ch].action = false;
  }
  else {
    Channels[ch].action = true;
  }
  Channels[ch].next = timerTicks + zxLoopDelay; // delay added to reach the next zx

  ++ch %= CHANNELS; // next channel

#ifdef WITH_CALIBRATION
  if (zxLoopCalibration.iterations < zxCalibrationLoops) {
    zxLoopCalibration.iterations++;
  }
#endif
}

#ifdef FAKE_HW
 #if defined(__AVR_ATmega328P__)
ISR(TIMER2_COMPA_vect) {    
  zeroCrossingIsr();
  // interrupt flag is cleared automatically by hardware
}
 #endif
#endif

// --TIMER ISR-----------------------------------------------------------------
void timerIsr(void)
{
  static uint32_t lastTicks = 0;

  // phase control for the fan 
  if (++phaseCounter > 90) {
    phaseCounter = 0;
  }

  digitalWrite(PIN_FAN, (phaseCounter > Channels[CHANNEL_FAN].target) ? LOW : HIGH);

  // wave packet control for heater
  if (Channels[CHANNEL_HEATER].next > lastTicks // FIXME: this looses ticks when overflowing
          && timerTicks > Channels[CHANNEL_HEATER].next)
  {
    digitalWrite(PIN_HEATER, Channels[CHANNEL_HEATER].action ? HIGH : LOW);
    lastTicks = timerTicks;
  }

  // handle encoder + button
  Encoder.service();

  timerTicks++;

#ifdef WITH_CALIBRATION
  if (zxLoopCalibration.iterations < zxCalibrationLoops) {
    zxLoopCalibration.measure[zxLoopCalibration.iterations]++;
  }
#endif
}
```

I don't understand how the zero crossing is working or here called "wave packet control for heater" ...

Channels[CHANNEL_HEATER].target is set by the PID value (0-100)

every second zerro crossing the value is added to .state 
if state >100 then state-=100 and action = false
else action = true

in timerIsr (called every 600us)
delayed by ~29ms
PIN_HEATER = action;

PIN_HEATER is low => Head on!

Why? we do not need the secound timer for that to work
It is not a Phase cutting. Is there a reason?

Maybe I'm just writing that to be sure that i did not overlooked something ....

**Comment by trueserve** [comment]
Sorry, going on memory here, it's been a while and I kinda hacked this to pieces...

Backstory:
I can't remember what his original code did, but it caused severe electrical interference...I could have probably filtered it maybe? But that just adds cost and more parts. Instead I changed the code to stay on for several periods, off for several periods, using zero crossing as the time to turn on / off.

Re: Timer2:
The Timer2 thing is if FAKE_HW is defined, this is to simulate zero crossing without AC connected. It isn't normally used.

**Comment by im-pro-at** [comment]
OK. Thanks for the answer ;-)

I will try Phase Cutting to get more control over the heating element.
